name: Node CI

on:
  push:
    branches:
      - "master"

jobs:
  build-node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - run: |
          yarn install
          yarn build
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - id: Deploy
        uses: google-github-actions/deploy-appengine@main
      - name: show url
        run: gcloud app describe
